name: Build Storybook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PACKAGE_DEPLOYER_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 17.0.0
          registry-url: https://npm.pkg.github.com/
      - run: |
          git fetch
          git config --global user.name "Shummy1991"
          git config --global user.email "shummy1991@gmail.com"
          git checkout storybook
          git merge main

      - run: npm ci
      - run: npm run build-storybook
      - run: rm -rf docs
      - run: mv storybook-static docs
      - run: |
          git add .
          git commit -m "new storybook build"
          git push
